<a href="https://colab.research.google.com/github/Matheus0820/Aprendizado-de-Maquina/blob/main/unidade01/codes/Algoritmo_para_an%C3%A1lise_de_sentimentos_em_textos_Aprendizado_de_M%C3%A1quina.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmo para análise de sentimentos em textos - Aprendizado de Máquina

**Aluno:** Matheus Ramos Ferreira da Silva

Aprendizado de Máquina 26.1

# Importação dos dados de análise

In [ ]:
# Bibliotecas usadas
import pandas as pd

# Importando base de dados
url = 'https://raw.githubusercontent.com/ect-info/ml/master/dados/Restaurant_Reviews.tsv'

df = pd.read_csv(url, sep='\t', quoting = 3)
df.head()

                                              Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

# Importando e configurando algumas bibliotecas importantes
- Lib. Natural Language Toolkit (nltk) → Possuem modelo pré-treinados para análise de sentimentos

- Lib. googletrans-py → Para a tradução do português para o inglês

In [ ]:
# Instalando o googletrans-py
!pip install googletrans-py

Requirement already satisfied: googletrans-py in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: httpx>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from googletrans-py) (0.28.1)
Requirement already satisfied: h2<5,>=4 in /usr/local/lib/python3.12/dist-packages (from googletrans-py) (4.3.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=4->googletrans-py) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=4->googletrans-py) (4.1.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.22.0->googletrans-py) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.22.0->googletrans-py) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.22.0->googletrans-py) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.22.0->googletrans-py) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.22.0->googletrans-py) (0.16.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx>=0.22.0->googletrans-py) (4.15.0)

In [ ]:
# Importando o NLTK e seu modelo pré-treinado
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Importando o Google Translator
from googletrans import Translator
translator = Translator()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

## Fazendo testes com texto em Português

In [ ]:
# Textos
listTextoPTBR = [
    "Oi. Como você está?",
    "Bom dia.",
    "Bom dia!",
    "Quero que o mundo de exploda hoje. Estou sem paciência para tudo!",
    "Que RAIVA! Todo mundo é idiota! Não gosto de pessoas!"
]

In [ ]:
# Traduzindo texto para o inglês
listTextoEN = []
for texto in listTextoPTBR:
  listTextoEN.append(translator.translate(texto, dest='en').text)

# Mostrando texto traduzidos
for texto in listTextoEN:
  print(f"- {texto}")
#

- Hi. How are you?
- Good morning.
- Good morning!
- I want the world to explode today.I have no patience for everything!
- What ANGER!Everyone is an idiot!I don't like people!

In [ ]:
# Fazendo a análise de sentimento desses textos
sid = SentimentIntensityAnalyzer()
for texto in listTextoEN:
  s = sid.polarity_scores(texto)
  print(f' -> Frase: "{texto}":')
  print(f"    - Percentual negativo: {s['neg'] * 100:.2f}%")
  print(f"    - Percentual positivo: {s['pos'] * 100:.2f}%")
  print(f"    - Percentual neutro: {s['neu'] * 100:.2f}%")
  print(f"    - Score Composto: {s['compound']:.4f}")

  # Determinando o sentimento geral
  if s['compound'] >= 0.05:
    sentiment = 'Positivo'
  elif s['compound'] <= -0.05:
    sentiment = 'Negativo'
  else:
    sentiment = 'Neutro'
  print(f"    - Sentimento: {sentiment}\n")

 -> Frase: "Hi. How are you?":
    - Percentual negativo: 0.00%
    - Percentual positivo: 0.00%
    - Percentual neutro: 100.00%
    - Score Composto: 0.0000
    - Sentimento: Neutro

 -> Frase: "Good morning.":
    - Percentual negativo: 0.00%
    - Percentual positivo: 74.40%
    - Percentual neutro: 25.60%
    - Score Composto: 0.4404
    - Sentimento: Positivo

 -> Frase: "Good morning!":
    - Percentual negativo: 0.00%
    - Percentual positivo: 76.10%
    - Percentual neutro: 23.90%
    - Score Composto: 0.4926
    - Sentimento: Positivo

 -> Frase: "I want the world to explode today.I have no patience for everything!":
    - Percentual negativo: 19.50%
    - Percentual positivo: 10.20%
    - Percentual neutro: 70.40%
    - Score Composto: -0.2942
    - Sentimento: Negativo

 -> Frase: "What ANGER!Everyone is an idiot!I don't like people!":
    - Percentual negativo: 29.90%
    - Percentual positivo: 0.00%
    - Percentual neutro: 70.10%
    - Score Composto: -0.4563
    - Sentimento: Negativo

## Analisando frases da base de dados

In [ ]:
# Analisando a base de dados
# Pegando as 5 primeiras frases da base de dados
frases_analise = df['Review'][0:5]

# Analisando o sentimento e mostrando
for frase in frases_analise:
  s = sid.polarity_scores(frase)
  print(f' -> Frase: "{frase}":')
  print(f"    - Percentual negativo: {s['neg'] * 100:.2f}%")
  print(f"    - Percentual positivo: {s['pos'] * 100:.2f}%")
  print(f"    - Percentual neutro: {s['neu'] * 100:.2f}%")
  print(f"    - Score Composto: {s['compound']:.4f}")

  # Determinando o sentimento geral
  if s['compound'] >= 0.05:
    sentiment = 'Positivo'
  elif s['compound'] <= -0.05:
    sentiment = 'Negativo'
  else:
    sentiment = 'Neutro'
  print(f"    - Sentimento: {sentiment}\n")

 -> Frase: "Wow... Loved this place.":
    - Percentual negativo: 0.00%
    - Percentual positivo: 56.50%
    - Percentual neutro: 43.50%
    - Score Composto: 0.5994
    - Sentimento: Positivo

 -> Frase: "Crust is not good.":
    - Percentual negativo: 44.50%
    - Percentual positivo: 0.00%
    - Percentual neutro: 55.50%
    - Score Composto: -0.3412
    - Sentimento: Negativo

 -> Frase: "Not tasty and the texture was just nasty.":
    - Percentual negativo: 34.00%
    - Percentual positivo: 0.00%
    - Percentual neutro: 66.00%
    - Score Composto: -0.5574
    - Sentimento: Negativo

 -> Frase: "Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.":
    - Percentual negativo: 9.30%
    - Percentual positivo: 32.20%
    - Percentual neutro: 58.50%
    - Score Composto: 0.6908
    - Sentimento: Positivo

 -> Frase: "The selection on the menu was great and so were the prices.":
    - Percentual negativo: 0.00%
    - Percentual positivo: 27.20%
    - Percentual neutro: 72.80%
    - Score Composto: 0.6249
    - Sentimento: Positivo

In [ ]:
# Classificando todos e gerando uma tabela com a classificação
for frase in df['Review']:
  s = sid.polarity_scores(frase)

  # Definindo o sentimento da frase no dataframe
  if s['compound'] >= 0.05:
    df.loc[df['Review'] == frase, 'sentiment'] = 'Positivo'
  elif s['compound'] <= -0.05:
    df.loc[df['Review'] == frase, 'sentiment'] = 'Negativo'
  else:
    df.loc[df['Review'] == frase, 'sentiment'] = 'Neutro'

# Mostrando DataFrame
df.head()

                                              Review  Liked sentiment
0                           Wow... Loved this place.      1  Positivo
1                                 Crust is not good.      0  Negativo
2          Not tasty and the texture was just nasty.      0  Negativo
3  Stopped by during the late May bank holiday of...      1  Positivo
4  The selection on the menu was great and so wer...      1  Positivo