<a href="https://colab.research.google.com/github/Matheus0820/Aprendizado-de-Maquina/blob/main/unidade01/codes/Aprendizado_de_M%C3%A1quina_Aula_Introdutoria_Unidade_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula Introdutória

## Prática 1

### → Exportar um Arquivo CSV (https://github.com/ect-comp/ml/tree/master/dados)

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/ect-comp/ml/refs/heads/master/dados/diabetes.csv"
df = pd.read_csv(url)

### → Abrir um DataFrame com Pandas

In [ ]:
print(f"DataFrame: \n")
df.head() # em df.head(x), x vai ser o total de linha nos quais quero que sejam exibidos

DataFrame:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

### → Visualizar alguns dados

In [ ]:
print(f"Todas as colunas do DataFrame: \n")
print(df.columns) # .columns vai mostrar todas as colunas do DataFrame

Todas as colunas do DataFrame:

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
print("Mostrando algumas colunas:")
df[['Glucose', 'BloodPressure', 'Age']].head(10) # Posso filtar as colunas nos quais quero exibir.

Mostrando algumas colunas:

   Glucose  BloodPressure  Age
0      148             72   50
1       85             66   31
2      183             64   32
3       89             66   21
4      137             40   33
5      116             74   30
6       78             50   26
7      115              0   29
8      197             70   53
9      125             96   54



---